[programs.localnet]
mysolanaapp = "4qSu5gHKQgFN775521GZN2L1rBMdg9jxxre3JmBroykW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gurujustin/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
